name: CI

on: [push, pull_request]

jobs:
  build-sample-on-linux:
    name: 'Build sample document on Linux'
    runs-on: ubuntu-latest
    steps:
      # Checks out the repository under $GITHUB_WORKSPACE,
      # so the job can access it
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Build sample with XeLaTeX
        uses: ./.github/actions/latexmk
        with:
          engine: '-xelatex'
          source: 'dissertation_template_latex_sample.tex'

      - name: Build sample with pdfLaTeX
        uses: ./.github/actions/latexmk
        with:
          engine: ''
          source: 'dissertation_template_latex_sample.tex'

      - name: Build template with XeLaTeX
        uses: ./.github/actions/latexmk
        with:
          engine: '-xelatex'
          source: 'dissertation_template_latex.tex'

      - name: Build template with pdfLaTeX
        uses: ./.github/actions/latexmk
        with:
          engine: ''
          source: 'dissertation_template_latex.tex'
